### ISSUE TITLE
Question about IGC Parser

### ISSUE THREAD

**Issue by vicb** [mmomtchev/igc-xc-score#1]
> I have included my own copy of igc-parser, otherwise available here, which is less zealous over the quality of the IGC files. You can use the original one or import/require my version which silently ignores IGC errors

I think that it would be nice to (try to) upstream those changes.

Also it would probably be a good idea to add the base version and the differences in your own copy.

I guess you tried the [lenient mode](https://github.com/Turbo87/igc-parser/blob/a95e1ac389c2dbf92510b30d2e5add7dc1c64953/index.ts#L166) of IGC Parser ?

**Comment by mmomtchev** [comment]
Sorry for the delay, but I was away (flying)
No, in fact I haven't seen it
I don't have unit tests for all the failing IGC cases, but for those I remember, the lenient options seems to do the job
I will recommend that everyone switches over to the official version (eventually using the lenient option) but I will keep the modified builtin for one more release

**Comment by vicb** [comment]
No problem. I hope you had good flights.

I submitted a few changes to the parser/lenient mode end of last year to support more common cases.

Nobody ever reported an issue since then and it's usually hundreds of tracks seen everyday on the ffvl website (recent + archives).
