### ISSUE TITLE
Possible speedup

### ISSUE THREAD

**Issue by vicb** [mmomtchev/igc-xc-score#12]
The algo currently optimize the score and the most expensive part is the computation of the distance.

Any win in the distance computation could result in a faster algo.

One thing to try would be to optimize score<sup>2</sup> instead.

This would remove one expensive `Math.sqrt()` from each distance computation and it could be applied only once one the outptut.

edit: I don't think it's possible to optimize score<sup>2</sup> but maybe there is still something to do with distance<sup>2</sup>

**Comment by mmomtchev** [comment]
This comes down next to nothing, it used to be like this in the very early versions - it will break compatibility with vincenty's and it does not apply to `maxDistancePath` which is the most time-consuming one
If you do it only for the rest - the gain is inferior than the statistical difference

**Comment by vicb** [comment]
Thanks for the answer. Closing then.
