### ISSUE TITLE
Demo not working in Windows browsers

### ISSUE THREAD

**Issue by johnstevenson** [mmomtchev/igc-xc-score#15]
Using the demo at https://www.meteo.guru/xc-score/ I get the following errors when uploading any IGC file:

Windows Chrome Version 90.0.4430.85 (Official Build) (64-bit)
`TypeError: Cannot read property 'parse' of undefined`

Windows Firefox Version 88.0 (64-bit)
`TypeError: igc_parser__WEBPACK_IMPORTED_MODULE_6__.IGCParser is undefined`

Windows Microsoft Edge Version 90.0.818.42 (Official build) (64-bit)
`TypeError: Cannot read property 'parse' of undefined`

**Comment by mmomtchev** [comment]
@johnstevenson I updated <https://www.meteo.guru/xc-score/> to the latest version

**Comment by johnstevenson** [comment]
Cool, thanks for fixing this.
