### ISSUE TITLE
FAI Triangle not getting the further points

### ISSUE THREAD

**Issue by volandoo** [mmomtchev/igc-xc-score#176]
Awesome library!

Checkout this track, the triangle does not get the most further points, we're using the FAI scoring rule
https://volandoo.com/tracks/d0FI2Jkb1nMItI9UQYlu

<img width="316" alt="Screenshot 2023-10-11 at 09 10 14" src="https://github.com/mmomtchev/igc-xc-score/assets/112556315/19c52c5c-0843-41af-aaa1-3cc47997a97f">

Is this expected? or is there any setting that can be adjusted?

**Comment by mmomtchev** [comment]
FAI scoring limits the closing of the triangle to 800m (two cylinders of 400m). The biggest triangle requires a closing of 820m - you can see it if you score the flight according to the FFVL rules which limit the closing to 3km.
