### ISSUE TITLE
Cannot read properties of undefined (reading 'heapUsed')

### ISSUE THREAD

**Issue by capsule5** [mmomtchev/igc-xc-score#21]
Hi, i enter a strange bug. your package works as expected in a parcel/vanilla JS  environnement, but in a webpack/vuejs environnement I got this error **Cannot read properties of undefined (reading 'heapUsed') at solver (line 70)**

 `const mem = process.memoryUsage(); `

mem is undefined ...

**Comment by capsule5** [comment]
Ok Parcel includes several features that emulate the Node.js API... I think that's why I could ran it on the client.

**Comment by mmomtchev** [comment]
@capsule5 this error is in `cli.js`, what are you including in Parcel? `cli.js` does not work without Node.js, you should be requiring the solver
