### ISSUE TITLE
Would you accept a PR to drop the collections package?

### ISSUE THREAD

**Issue by vicb** [mmomtchev/igc-xc-score#234]
Integrating igc-xc-score in flyxc.app breaks the app.

The root cause is the [`collections`](https://www.npmjs.com/package/collections) package:

> Design principles: extends core types (e.g extends Array.prototype with additional non-enumerable properties like .set)

I can create a PR to replace it with another package not polluting the global namespace.

Would that be ok?

Ref: https://github.com/vicb/flyxc/pull/203

cc @flyingtof

**Comment by mmomtchev** [comment]
I removed the `Map` which was no longer needed, `SortedSet` is required however, if you can find another package that implements a sorted set, sure

**Comment by vicb** [comment]
Cool, thank you so much.

What about https://www.npmjs.com/package/@rimbu/sorted?

It seems popular enough, maintained, and clean code.
It works on the most popular runtime both server side and client side.

**Comment by laggery** [comment]
Hi @vicb

Have you already started the implementation?
I have the same need and maybe I could help you with the implementation.
Best regards
Yannick

**Comment by vicb** [comment]
@laggery not yet.

For now we did import igc-xc-score in a web worker to isolate the side effects.

Our plan is to fork this package into https://github.com/vicb/flyxc and  clean the package there (and publish to npm from there)

**Comment by laggery** [comment]
@vicb Thank you very much for your quick reply.

To be able to finish my update, I will try  the web worker workaround.

**Comment by vicb** [comment]
You can check `apps/fxc-front/src/app/workers/optimizer.ts` and where it is loaded in flyxc

**Comment by vicb** [comment]
Closing as the `SortedSet`  does not look to pollute the global namespace.
