### ISSUE TITLE
Properties "launch" and "landing" missing in index.d.ts file ?

### ISSUE THREAD

**Issue by xeronimus** [mmomtchev/igc-xc-score#245]
The solver detects launch and landing automatically. 
The resulting ```Solution``` contains indices for both these points.  

E.g. 
```javascript
{
  opt: {
    launch: 0,             // the index of the corresponding GPS fix
    landing: 1247,     // the index of the corresponding GPS fix
    flight: { ... },
    scoring: { ... },
    config : {... }
  },
  ...
}
```

The type ["Opt"](https://github.com/mmomtchev/igc-xc-score/blob/6ef05c2f66a8b51131ed9626f111a026ca8b1ef4/index.d.ts#L50), that is defined in index.d.ts is missing the two properties "launch" and "landing".

- Would you accept a PR to add those two properties?
- Are they always set, or should they be defined as optional properties?

```typescript

interface Opt {
	scoring: Scoring;
	flight: IGCFile & {
		/** Filtered GPS fixes when invalid=false, GPS fix number is relative to this array */
		filtered: BRecord[];
	};
	launch?: number;
        landing?: number;
}

```

Thanks!

**Comment by mmomtchev** [comment]
As far as I remember, they are optional and depend on whether the launch/landing detection is enabled.

You can submit a PR.

**Comment by xeronimus** [comment]
I checked the code, "launch" and "landing" are always set.

If launch-landing detection is disabled (or no launch/landing can be detected), "launch" will be 0 and "landing" will be the index of the last fix.

the ```Solution.Opt``` also contains the config object, I added it to the type definition as well.
